language: node_js
node_js: stable

# assign build branches
branches:
  only:
    - blog-source

# cache this directory
cache:
  directories:
    - node_modules
# S: Build Lifecycle
before_install:
  - openssl aes-256-cbc -K encrypted_5e9b2e7299ba_key -iv encrypted_5e9b2e7299ba_iv -in ./.travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - npm install -g hexo-cli # 安装 hexo

install:
  - npm install # 安装 package.json 中的插件

script:
  - hexo generate

after_success:
  - git config --global user.name "4pmtong"
  - git config --global user.email "web_chentong@163.com"
  - sed -i'' "/^ *repo/s~github\.com~${githubToken}@github.com~" _config.yml
  - hexo deploy
# E: Build LifeCycle
